config/routes.rb
Thedecider::Application.routes.draw do

  devise_for :users
  resources :users

  resources :alternatives
  resources :decisions
  resources :factors
  resources :rankings

  get "home/welcome"
  get "home/about"

  root :to => 'home#welcome'

end

app/models/decision.rb
class Decision < ActiveRecord::Base

  belongs_to :user

  # just in case -- "design for evil clients"
  validates_presence_of :user_id

  # this has security applied in controller; see can_access call
  attr_accessible :user_id

  has_many :alternatives, :dependent => :destroy
  has_many :factors, :dependent => :destroy
  has_many :rankings, :through => :alternatives  # could also say thru factors

  accepts_nested_attributes_for :alternatives, :factors, :rankings, :allow_destroy => true

  attr_accessible :alternatives_attributes, :factors_attributes, :rankings_attributes

  attr_accessible :name
  validates :name, :length => { :minimum => 2, :maximum => 50 },
            :presence => true,
            :uniqueness => true

  attr_accessible :public

  # hmmm, maybe this is redundant?
  def public?
    @public
  end

end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController

  before_filter :get_decision, except: [ :index, :new, :create ]

  # GET /decisions
  # GET /decisions.json
  def index
    @show_all = @user.is_admin?
    @decisions = @show_all ? Decision.all : current_user.decisions
    @title = "#{@user.is_admin? ? 'Everybody' : @user.username}'s Decisions"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decisions }
    end
  end

  def show
    @title = @decision.name
    respond_to do |format|
      format.html
      format.json { render json: @decision }
    end
  end

  # GET /decisions/new
  # GET /decisions/new.json
  def new
    @title = 'New Decision'
    @decision = Decision.new
    @show_all = @user.is_admin?
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @decision }
    end
  end

  # GET /decisions/1/edit
  def edit
    @title = 'Edit Decision'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @decision }
    end
  end

  # POST /decisions
  # POST /decisions.json
  def create
    @title = 'New Decision'
    @decision = Decision.new(params[:decision])
    @decision.user_id = current_user.id
    @show_all = @user.is_admin?
    respond_to do |format|
      if @decision.save
        format.html { redirect_to edit_decision_path(@decision),
                      notice: 'Decision was successfully created.' }
        format.json { render json: @decision, status: :created, location: @decision }
      else
        format.html { render action: "new" }
        format.json { render json: @decision.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  # PUT /decisions/1
  # PUT /decisions/1.json
  def update
    @title = 'Edit Decision'
    respond_to do |format|
      if @decision.update_attributes(params[:decision])
        format.html { redirect_to edit_decision_path(@decision),
                      notice: 'Decision was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: :edit }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision.destroy
    respond_to do |format|
      format.html { redirect_to decisions_path,
                    notice: 'Decision was successfully destroyed.' }
      format.json { head :ok }
    end
  end


  ##############################
  ##                          ##
  ##  PRIVATE METHODS BELOW!  ##
  ##                          ##
  ##############################


  private

  def get_decision
    @decision = Decision.find params[:id], include: [ :alternatives, :factors, :rankings ]
    # ORDER IS IMPORTANT!  If current_user is nil and we get to can_access, it will redirect.
    @decision = nil unless @decision.nil? || (@decision.public? && params[:action] == 'show') || can_access(@decision)
  end

end

app/helpers/decisions_helper.rb
module DecisionsHelper
  def set_decision_view_stuff
    @show_all = @user && @user.is_admin?
    max = 0
    tmp_ranks = Ranking.where(factor_id: @decision.factors.map(&:id)).
                        where(alternative_id: @decision.alternatives.map(&:id))
    @rankings = {}
    points = Hash.new 0
    @weightNames = {}
    @decision.factors.each do |fac|
      fac.weight_id = Level::Medium if ! fac.weight_id
      @weightNames[fac.id] = Level::weightNames[fac.weight_id-1]
      max += fac.weight
      @decision.alternatives.each do |alt|
        rank = tmp_ranks.find { |r|
          r.alternative_id == alt.id && r.factor_id == fac.id
        }
        if ! rank
          rank = Ranking.new
          rank.alternative_id = alt.id
          rank.factor_id = fac.id
          rank.weight_id = Level::Medium
          rank.save!
        end
        @rankings[[alt.id,fac.id]] = rank
        points[alt.id] += rank.weight * fac.weight
      end
    end
    max *= Level::Count

    @scores = {}
    @percents = Hash.new 0
    ptsPerLevel = (max + 1.0) / Level::Count
    if points.length > 0
      @decision.alternatives.each do |alt|
        level = (points[alt.id] / ptsPerLevel).to_i
        @scores[alt.id] = level
      end
      points.map { |key, val| @percents[key] = val * 100.0 / max }
    else
      @decision.alternatives.map do |alt|
        @percents[alt.id] = 0
        @scores[alt.id] = Level::Medium
      end
    end
  end
end

app/views/decisions/_form.html.erb
<%# TODO: DRY this with show! %>
<% set_decision_view_stuff %>
<% sorted_alts = @decision.alternatives.sort_by { |alt| -@percents[alt.id] } %>
<% sorted_facts = @decision.factors.sort_by { |fact| -fact.weight } %>

<% if @decision.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@decision.errors.count, "error") %>
    prohibited this decision from being saved:
    </h2>
    <ul>
      <% @decision.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @decision do |decform| %>

  <div align="center">
    <%= decform.label :name, class: 'attr_label' %>:
    <%= decform.text_field :name, class: 'attr_field' %>
    <%# won't have a user_id on #new! %>
    <% if @user.is_admin? && @decision.user_id && @decision.user_id != @user.id %>
      <br/>(from <%= @decision.user.username %>)
    <% end %>
    <br/><%= decform.label :public? %>: <%= decform.check_box :public? %>
    <br/>
  </div>

  <p/>
  <table align="center" border="1">
    <tr valign="top">
      <td>
        <%= link_to 'Add Alternative (column)',
            new_alternative_path( :decision_id => @decision.id ),
            class: 'add_item_link' %>
        <br/>
        <%= link_to 'Add Factor (row)',
            new_factor_path( :decision_id => @decision.id ),
            class: 'add_item_link'  %>
      </td>

      <%= decform.fields_for :alternatives, sorted_alts do |altform| %>
        <td>
          <%= altform.text_field :name, class: 'attr_field', size: 10 %><br/>
          <%= altform.label :_destroy, 'Remove', class: 'remove_item_label' %>
          <%= altform.check_box :_destroy %>
        </td>
      <% end %>

    </tr>

    <%= decform.fields_for :factors, sorted_facts do |facform| %>
      <tr>
        <td>
          <%= facform.text_field :name, class: 'attr_field', size: '20' %><br/>
          <%= facform.collection_select(:weight_id,
                                        Level.weightNames, :id, :name,
                                        { selected: facform.object.weight } ) %>
          <%= facform.label :_destroy, 'Remove', class: 'remove_item_label' %>
          <%= facform.check_box '_destroy' %>
        </td>
        <% sorted_alts.each do |alt| %>
          <% rank = @rankings[[alt.id,facform.object.id]] %>
          <td bgcolor="<%= Level.goodColors[rank.weight - 1].name %>">
            <%= decform.fields_for :rankings, rank do |rankform| %>
              <%= rankform.collection_select(:weight_id,
                                             Level.goodNames, :id, :name,
                                             selected: rank.weight) %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>

    <tr>
      <td>Results:</td>

      <% sorted_alts.each do |alt| %>
        <td bgcolor="<%= Level.goodColors[@scores[alt.id]].name %>"
            class="rating">
          <%= Level.goodNames[@scores[alt.id]].name %><br/>
          (<%= number_to_percentage @percents[alt.id], precision: 0 %>)
        </td>
      <% end %>
    </tr>
  </table>
  <div align="center"><%= decform.submit '   Save   ', disable_with: 'Saving....' %></div>
<% end %>

<div id="back_link"><%= link_to 'Back to Decisions', decisions_path %></div>

app/views/decisions/edit.html.erb
<%= render 'form' %>

app/views/decisions/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <% if @show_all %>
      <th>User</th>
    <% end %>
    <th></th>
    <th></th>
  </tr>

<% @decisions.each do |decision| %>
  <tr>
    <td><%= link_to decision.name, edit_decision_path(decision) %></td>
    <% if @show_all %>
      <td><%= decision.user ? decision.user.username : "ERROR: NO USER" %></td>
    <% end %>
    <td><%= link_to 'Destroy', decision,
                               confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Decision', new_decision_path %>

app/views/decisions/new.html.erb
<%= render 'form' %>

app/views/decisions/show.html.erb
<%# TODO: DRY this with _form! %>
<% set_decision_view_stuff %>
<% sorted_alts = @decision.alternatives.sort_by { |alt| -@percents[alt.id] } %>
<% sorted_facts = @decision.factors.sort_by { |fact| -fact.weight } %>

<%# decision name is already in title %>
<% if @user.nil? || @user.id != @decision.user_id %>
  <div id="author">(author: <%= @decision.user.username %>)</div>
<% end %>

<p/>
<table align="center" border="1">
  <tr valign="top">
    <td></td>

    <% sorted_alts.each do |alt| %>
      <td bgcolor="<%#= Level.goodColors[@scores[alt.id]].name %>" >
        <%= alt.name %>
      </td>
    <% end %>

  </tr>

  <% sorted_facts.each do |fac| %>
    <tr>
      <td>
        <%= fac.name %><br/>
        <div class="weight">
          (Weight: <%= Level.weightNames[fac.weight_id-1].name %>)
        </div>
      </td>
      <% sorted_alts.each do |alt| %>
        <% rank = @rankings[[alt.id,fac.id]] %>
        <td bgcolor="<%= Level.goodColors[rank.weight-1].name %>" class="rating">
          <%= Level.goodNames[rank.weight-1].name %>
        </td>
      <% end %>
    </tr>
  <% end %>

  <tr>
    <td>Results:</td>

    <% sorted_alts.each do |alt| %>
      <td class="rating" bgcolor="<%= Level.goodColors[@scores[alt.id]].name %>">
        <%= Level.goodNames[@scores[alt.id]].name %><br/>
        (<%= number_to_percentage @percents[alt.id], precision: 0 %>)
      </td>
    <% end %>
  </tr>
</table>